// Materialize each book's licence record into its chapters' frontmatter.
//
// Usage (from site/):
//   npm run books          # write
//   npm run check:books    # exit non-zero if any chapter is stale
//
// content/research/books/<id>/book.yml is the SOURCE OF TRUTH for the four fields a whole
// book shares — license, license_file, attribution, derived. They are copied into every
// chapter rather than merged in at validation time, so a chapter note validates from its own
// frontmatter like every other note in the corpus: no file I/O inside a zod schema, and a
// kind manifest that reports what a book chapter actually carries.
//
// The copy is what makes this a generated artifact, and --check in CI is what keeps a copy
// from becoming a second source of truth — the same trade kinds.generated.json makes.

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import yaml from 'js-yaml';

const BOOKS_DIR = path.resolve('../content/research/books');

// The managed block is delimited so regeneration is idempotent and an author can see at a
// glance that editing these four lines is pointless. Anything outside the markers is the
// chapter's own frontmatter and is never touched.
const BEGIN = '# --- book.yml (generated by `npm run books`) — edit book.yml, not here ---';
const END = '# --- end book.yml ---';

/** The book-level fields copied into every chapter, in the order they are written. */
const MANAGED = ['license', 'license_file', 'attribution', 'derived'] as const;

interface BookMeta {
  license?: unknown;
  license_file?: unknown;
  attribution?: unknown;
  derived?: unknown;
}

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

/**
 * The managed block for one chapter, already YAML-escaped.
 *
 * `attribution` may be a template — {n} and {title} are filled from the chapter, because this
 * is the one book-level field that cites the chapter it appears on. Rendered through js-yaml
 * rather than string-concatenated so a title containing a colon or a quote cannot produce
 * frontmatter that parses differently than it reads.
 */
function managedBlock(book: BookMeta, chapter: Record<string, unknown>, source: string): string {
  const fields: Record<string, string> = {};
  for (const key of MANAGED) {
    const value = book[key];
    if (value === undefined || value === null) {
      // license_file is genuinely optional (an own-words book redistributes no text and
      // carries no upstream LICENSE); the other three are not.
      if (key === 'license_file') continue;
      fail(`${source}/book.yml: missing required field \`${key}\``);
    }
    fields[key] =
      key === 'attribution'
        ? String(value)
            .replace(/\{n\}/g, String(chapter.source_chapter ?? ''))
            .replace(/\{title\}/g, String(chapter.title ?? ''))
        : String(value);
  }
  const body = yaml.dump(fields, { lineWidth: -1, quotingType: '"' }).trimEnd();
  return `${BEGIN}\n${body}\n${END}`;
}

/** Split a note into its frontmatter body and everything after it. */
function splitNote(text: string, file: string): { frontmatter: string; rest: string } {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---(\r?\n|$)/);
  if (!match) fail(`${file}: no frontmatter block`);
  return { frontmatter: match[1]!, rest: text.slice(match[0].length) };
}

/**
 * Drop any previously generated block.
 *
 * Scanned line by line rather than matched with a regex built from the markers: the markers
 * contain `(`, `)` and `-`, so a regex built from them silently matches nothing and every run
 * appends a second block instead of replacing the first.
 */
function stripManaged(frontmatter: string, file: string): string {
  const out: string[] = [];
  let inside = false;
  for (const line of frontmatter.split('\n')) {
    if (line.trim() === BEGIN) {
      if (inside) fail(`${file}: nested \`${BEGIN}\` marker`);
      inside = true;
      continue;
    }
    if (line.trim() === END) {
      if (!inside) fail(`${file}: \`${END}\` with no opening marker`);
      inside = false;
      continue;
    }
    if (!inside) out.push(line);
  }
  if (inside) fail(`${file}: unterminated generated block (no \`${END}\`)`);
  return out.join('\n').trimEnd();
}

/**
 * Rewrite one chapter's frontmatter with the current managed block.
 *
 * The block is anchored immediately before `tags:` so the generated fields land where a
 * source note carries them (provenance, then the note envelope) and the position does not
 * drift between runs. A previous block is removed first, which is what makes this idempotent.
 */
function render(text: string, book: BookMeta, source: string, file: string): string {
  const { frontmatter, rest } = splitNote(text, file);
  const stripped = stripManaged(frontmatter, file);

  const chapter = yaml.load(stripped) as Record<string, unknown> | undefined;
  if (!chapter || typeof chapter !== 'object') fail(`${file}: frontmatter is not a mapping`);

  const block = managedBlock(book, chapter, source);
  const lines = stripped.split('\n');
  const anchor = lines.findIndex((l) => /^tags:/.test(l));
  if (anchor === -1) fail(`${file}: no \`tags:\` line to anchor the generated block before`);

  const merged = [...lines.slice(0, anchor), ...block.split('\n'), ...lines.slice(anchor)];
  return `---\n${merged.join('\n')}\n---\n${rest.replace(/^\r?\n/, '')}`;
}

function chaptersOf(bookDir: string): string[] {
  // `**/index.md` only — the same files the Astro loader and the corpus validator see.
  // A chapter's sibling guidance.md / a book's summary-prompt.md are not notes.
  return fs
    .readdirSync(bookDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => path.join(bookDir, e.name, 'index.md'))
    .filter((f) => fs.existsSync(f))
    .sort();
}

function main(argv: string[]): void {
  const unknown = argv.filter((f) => f !== '--check');
  if (unknown.length) {
    // An unrecognized flag is an error, not a no-op: `--chekc` must not silently fall through
    // to the write branch and overwrite the files the caller asked us to check.
    process.stderr.write('Usage: vite-node scripts/generate-book-frontmatter.ts [--check]\n');
    process.exit(2);
  }
  const check = argv.includes('--check');

  const books = fs
    .readdirSync(BOOKS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const stale: string[] = [];
  let written = 0;
  let chapters = 0;

  for (const source of books) {
    const bookDir = path.join(BOOKS_DIR, source);
    const metaFile = path.join(bookDir, 'book.yml');
    if (!fs.existsSync(metaFile)) fail(`${source}: no book.yml`);
    const book = yaml.load(fs.readFileSync(metaFile, 'utf-8')) as BookMeta;

    for (const file of chaptersOf(bookDir)) {
      chapters++;
      const current = fs.readFileSync(file, 'utf-8');
      const next = render(current, book, source, file);
      if (current === next) continue;
      if (check) stale.push(path.relative(path.resolve('..'), file));
      else {
        fs.writeFileSync(file, next);
        written++;
      }
    }
  }

  if (check) {
    if (stale.length) {
      process.stderr.write(
        `${stale.length} of ${chapters} book chapters are stale — run \`npm run books\` and commit:\n` +
          `${stale.map((f) => `  ${f}`).join('\n')}\n`,
      );
      process.exit(1);
    }
    process.stdout.write(`${chapters} book chapters across ${books.length} books are up to date.\n`);
  } else {
    process.stdout.write(
      `Wrote ${written} of ${chapters} book chapters across ${books.length} books.\n`,
    );
  }
}

main(process.argv.slice(2));
